//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string date { get; set; }
        public string votes { get; set; }
        public string tags { get; set; }
        public string status { get; set; }
    }
}
